### PR TITLE
Allow for missing parentId keys on root objects

### PR DESCRIPTION
**Pull request by manwaring**
I love this library!  On a recent project I realized that it doesn't work well with databases that don't save null/empty keys (looking at you DynamoDB).  This PR updates the logic so that objects with missing parentId keys are treated as root objects, rather than dropping objects without an existing parentId field set to null.

E.g. before the change the following snippet would result in an empty array because the first item has no parentId field and so is dropped, resulting in the second item not having a matching parent and so also being dropped.  With this PR the output would be the first item as root object, and second item as child to that.
```ts
const tree = arrayToTree([
    { id: '4', custom: 'abc' },
    { id: '31', parentId: '4', custom: '12' }
])
```

I also added an .npmignore file because I noticed in the code I pulled down that it was including the source and spec files in addition to the compiled code.

-----

While working in the code I noticed that the tests are running against the compiled/built code (I discovered this because originally tried to exclude the spec files from npm publishing by adding them to tsconfig exclude, but then the tests didn't run).  It's not very difficult to run tests against typescript files directly, without needing a build step ahead of time.  I'd be happy to update the project configuration to support that if it would be helpful.

### CODE REVIEW

**Comment by manwaring** [comment]
The build and tests all passed - it looks like the failure was in publishing to coveralls:

image

**Comment by philipstanislaus** [comment]
Thanks for your PR! THis sounds like a very useful addition - I’ll be able to look into this at the end of the week.

**Comment by manwaring** [comment]
Awesome, glad to hear it!  Let me know if there's anything you'd like me to change, I'm happy to adjust what I've written to adhere to project standards, etc.

**Comment by philipstanislaus** [comment]
Hey @manwaring , sorry for my very late reply – I completely forgot about your PR. 

I changed your logic to check for undefined instead of falsy values, which would have been any of the following: `0`, `""`, `false`...

Since I can't push to your branch, I'm closing your PR but will merge your changes as part of #14 .

Regarding tests: You are absolutely right, tests should run against TypeScript files. The reason they are not is an artifact to make them compatible with coverage reporting through Istanbul, see #8. I'm happy to merge a PR that upgrades Istanbul and removes the compilation step, if you are still interested in helping with that. 

Many thanks for your contribution!

**Comment by philipstanislaus** [comment]
Released in version 1.3.0

**Pull request closed without merging**
